version: "3.8"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1041
      - VERSION=docker
      - UMASK_SET=022 #optional
    volumes:
      - .config/:/config
      - /srv/share/media/tv:/tv
      - /srv/share/media/tv/movies:/movies
    restart: unless-stopped
