version: "3.8"

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1041
      - VERSION=docker
      - TZ='America/New_York'
      - UMASK_SET=022 #optional
    volumes:
      - ./config/:/config
      - /srv/share/media:/data
#      - /somewhere:/transcode
    restart: unless-stopped
