# Beets configuration --------------------------------------------------------

directory: /srv/share/media/music
library: ~/.config//beets/musiclibrary.blb
statefile: ~/.config/beets/state.pickle
time_format: '%Y-%m-%d %H:%M:%S'

import:
    # write metadata to music files
    write: yes

    # move imported files from source to the music directory
    move: yes
    copy: no
    delete: no

    # use auto-tagging where possible
    # do not require confirmation on strong matches
    autotag: yes
    timid: no

    resume: ask
    incremental: yes
    none_rec_action: ask
    #log:

    quiet: no  # enable with command line option
    quiet_fallback: skip
    default_action: apply

    duplicate_action: ask
    singletons: no
    languages: [en]
    detail: no
    flat: no
    log: ~/.config/beets/beet.log

asciify_paths: yes
# use the release-date of the original (first) release of an album?
original_date: no

# on multi-disk releases, assign track numbers for the whole album.
# If "per disk", make sure tracknames do not collide ("paths" setting).
per_disc_numbering: yes

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg", "*.m3u", "*.log", "*.cue"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]


# Paths ----------------------------------------------------------------------

# Paths and filenames for music files
# relative to music directory
paths:
    default: %the{$albumartist}/$album ($year)/$track $title
    singleton: Singles/$artist - $title
    comp: Compilations/$album/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

# replace special characters in generated filenames
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

path_sep_replace: _

# filename for the album art
art_filename: cover  # results in "cover.jpg"

max_filename_length: 0  # unlimited


# General --------------------------------------------------------------------

# use mutliple threads during import
threaded: yes
timeout: 5.0
verbose: yes


# User Interface -------------------------------------------------------------

color: yes
list_format_item: %upper{$artist} - $album - $track. $title
list_format_album: %upper{$albumartist} - $album
time_format: '%Y-%m-%d %H:%M:%S'
terminal_encoding: utf8

ui:
    terminal_width: 80
    length_diff_thresh: 10.0


# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.10      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: [unmatched_tracks]
    track_length_grace: 10
    track_length_max: 30


# Plugins --------------------------------------------------------------------

plugins: [
    #discogs,
    #lyrics,
    #echonest_tempo,
    fetchart,
    #acousticbrainz,
    embedart,
    lastgenre,
    #chroma,
    scrub,
    mbsync,
    #mpdupdate,
    #mpdstats,
    edit,
    the,
    missing,
    duplicates,
    #web,
    fromfilename
]
pluginpath: []


# Plugins Config -------------------------------------------------------------

#lyrics:
    #auto: yes
    #fallback: ''

#echonest_tempo:
 #   auto: yes

#discogs:
    #source_weight: 0.0

lastgenre:
   # whitelist: ~/.config/beets/genres.txt
    #canoncical: ~/.config/beets/genres-tree.yaml
    #fallback: ''
    auto: yes
    source: album

fetchart:
    auto: yes
    #maxwidth: 600
    #cautious: no
    #cover_names: cover folder back
    #google_key: REDACTED
    #google_engine: 001442825323518660753:hrh5ch1gjzm

embedart:
    auto: yes
    maxwidth: 600

replaygain:
    auto: yes
    overwrite: yes
    albumgain: yes

scrub:
    auto: yes

# required for mpdstats
#mpd:
    #host: localhost
    #port: 6600
    #password:  # none

# musicbrainz:
#     host: 192.168.1.200:5000
#     ratelimit: 100
musicbrainz:
    host: musicbrainz.org
    ratelimit: 1
    ratelimit_interval: 1.0
    searchlimit: 3
mpdstats:
    rating: False
    # two ratings are calculated:
    # "rolling" based on recent development
    # "stable" based on all-time development
    # rating mix 0.0 is all "rolling", 1.0 is all "stable"
    rating_mix: 0.75

missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no

duplicates:
    checksum: no  # expensive
