version: "3"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1041
      - TZ='America/New_York'
      - UMASK=002
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - /srv/share/media/downloads:/downloads
    ports:
      - 44488:44448
      - 36278:36278/udp
      - 8080:8080
    restart: unless-stopped
