version: "3"

services:
  medusa:
    image: linuxserver/medusa
    container_name: medusa
    environment:
      - PUID=1001
      - PGID=965
      - TZ='America/New_York'
    volumes:
      - ./config:/config
      - /srv/share/media:/downloads
      - /srv/share/media:/tv
    ports:
      - 8081:8081
    restart: unless-stopped
