version: "3"

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=965
      - TZ='America/New_York'
      - UMASK_SET=022 #optional
    volumes:
      - ./config:/config
      - /srv/share/media:/tv
      - /srv/share/media:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
