version: "3.8"

services:
  sonarr:
    image: binhex/arch-sonarr
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1001
      - PGID=1041
      - TZ='America/New_York'
      - UMASK=002
    volumes:
      - ./config:/config
      - /srv/share:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
      - 9897:9897
    restart: unless-stopped

networks:
  default:
    external:
      name: bridge
