version: "3"

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1041
      - TZ='America/New_York'
      - UMASK=002
    volumes:
      - ./config:/config
      - /srv/share/media/tv:/tv
      - /srv/share/media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
